import Foundation
@testable import mcs
import Testing

struct LockfileTests {
    private func makeTmpDir() throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("mcs-lockfile-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    private func makeEntry(
        identifier: String,
        commitSHA: String = "abc123def456"
    ) -> PackRegistryFile.PackEntry {
        PackRegistryFile.PackEntry(
            identifier: identifier,
            displayName: identifier,
            author: nil,
            sourceURL: "https://example.com/\(identifier)",
            ref: nil,
            commitSHA: commitSHA,
            localPath: identifier,
            addedAt: "2026-01-01T00:00:00Z",
            trustedScriptHashes: [:],
            isLocal: nil
        )
    }

    private func makeLocalEntry(
        identifier: String,
        localPath: String = "/Users/dev/local-pack"
    ) -> PackRegistryFile.PackEntry {
        PackRegistryFile.PackEntry(
            identifier: identifier,
            displayName: identifier,
            author: nil,
            sourceURL: localPath,
            ref: nil,
            commitSHA: "local",
            localPath: localPath,
            addedAt: "2026-01-01T00:00:00Z",
            trustedScriptHashes: [:],
            isLocal: true
        )
    }

    // MARK: - Generation

    @Test("Generate lockfile from registry entries and selected packs")
    func generateLockfile() {
        let entries = [
            makeEntry(identifier: "ios", commitSHA: "sha-ios"),
            makeEntry(identifier: "web", commitSHA: "sha-web"),
            makeEntry(identifier: "unselected", commitSHA: "sha-unused"),
        ]

        let lockfile = Lockfile.generate(
            registryEntries: entries,
            selectedPackIDs: ["ios", "web"]
        )

        #expect(lockfile.lockVersion == 1)
        #expect(lockfile.mcsVersion == MCSVersion.current)
        #expect(lockfile.packs.count == 2)
        #expect(lockfile.packs[0].identifier == "ios")
        #expect(lockfile.packs[0].commitSHA == "sha-ios")
        #expect(lockfile.packs[1].identifier == "web")
        #expect(lockfile.packs[1].commitSHA == "sha-web")
    }

    @Test("Generate lockfile only includes selected packs")
    func generateExcludesUnselected() {
        let entries = [
            makeEntry(identifier: "ios"),
            makeEntry(identifier: "web"),
        ]

        let lockfile = Lockfile.generate(
            registryEntries: entries,
            selectedPackIDs: ["ios"]
        )

        #expect(lockfile.packs.count == 1)
        #expect(lockfile.packs[0].identifier == "ios")
    }

    // MARK: - Persistence

    @Test("Save and load lockfile round-trips correctly")
    func saveAndLoad() throws {
        let tmpDir = try makeTmpDir()
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let lockfile = Lockfile.generate(
            registryEntries: [makeEntry(identifier: "ios", commitSHA: "sha123")],
            selectedPackIDs: ["ios"]
        )
        try lockfile.save(projectRoot: tmpDir)

        let loaded = try Lockfile.load(projectRoot: tmpDir)
        #expect(loaded != nil)
        #expect(loaded?.packs.count == 1)
        #expect(loaded?.packs[0].identifier == "ios")
        #expect(loaded?.packs[0].commitSHA == "sha123")
        #expect(loaded?.lockVersion == 1)
    }

    @Test("Load returns nil when no lockfile exists")
    func loadMissing() throws {
        let tmpDir = try makeTmpDir()
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let loaded = try Lockfile.load(projectRoot: tmpDir)
        #expect(loaded == nil)
    }

    @Test("Saved lockfile contains header comment")
    func headerComment() throws {
        let tmpDir = try makeTmpDir()
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let lockfile = Lockfile.generate(
            registryEntries: [makeEntry(identifier: "ios")],
            selectedPackIDs: ["ios"]
        )
        try lockfile.save(projectRoot: tmpDir)

        let path = tmpDir.appendingPathComponent("mcs.lock.yaml")
        let content = try String(contentsOf: path, encoding: .utf8)
        #expect(content.hasPrefix("# Auto-generated by mcs sync"))
    }

    // MARK: - Mismatch Detection

    @Test("No mismatches when SHAs match")
    func noMismatches() {
        let lockfile = Lockfile.generate(
            registryEntries: [makeEntry(identifier: "ios", commitSHA: "sha1")],
            selectedPackIDs: ["ios"]
        )
        let mismatches = lockfile.detectMismatches(
            registryEntries: [makeEntry(identifier: "ios", commitSHA: "sha1")]
        )
        #expect(mismatches.isEmpty)
    }

    @Test("Detects SHA mismatch")
    func shaMismatch() {
        let lockfile = Lockfile.generate(
            registryEntries: [makeEntry(identifier: "ios", commitSHA: "locked-sha")],
            selectedPackIDs: ["ios"]
        )
        let mismatches = lockfile.detectMismatches(
            registryEntries: [makeEntry(identifier: "ios", commitSHA: "different-sha")]
        )
        #expect(mismatches.count == 1)
        #expect(mismatches[0].identifier == "ios")
        #expect(mismatches[0].lockedSHA == "locked-sha")
        #expect(mismatches[0].currentSHA == "different-sha")
    }

    @Test("Detects missing pack in registry")
    func missingPack() {
        let lockfile = Lockfile.generate(
            registryEntries: [makeEntry(identifier: "ios", commitSHA: "sha1")],
            selectedPackIDs: ["ios"]
        )
        let mismatches = lockfile.detectMismatches(registryEntries: [])
        #expect(mismatches.count == 1)
        #expect(mismatches[0].identifier == "ios")
        #expect(mismatches[0].currentSHA == nil)
    }

    // MARK: - Local pack lockfile behavior

    @Test("Local pack is included in lockfile with commitSHA 'local'")
    func localPackInLockfile() {
        let entries = [
            makeEntry(identifier: "ios", commitSHA: "sha-ios"),
            makeLocalEntry(identifier: "my-local", localPath: "/path/to/my-local"),
        ]

        let lockfile = Lockfile.generate(
            registryEntries: entries,
            selectedPackIDs: ["ios", "my-local"]
        )

        #expect(lockfile.packs.count == 2)
        let localPack = lockfile.packs.first { $0.identifier == "my-local" }
        #expect(localPack?.commitSHA == "local")
    }
}
